# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoApplication' do

pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Alamofire', '~> 4.4'
pod 'SCLAlertView'
pod 'ReachabilitySwift', '~> 3'
pod 'KVNProgress'
pod 'IQKeyboardManagerSwift', '4.0.8'
pod 'SDWebImage'
pod 'Cosmos', '~> 12.0'


  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoApplication

  target 'DemoApplicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
